openapi: 3.0.3
info:
  title: Dispatch API
  version: 1.0.0
  description: API zur Erstellung Abfrage und Stornierung von Dispatch-Aufträgen

servers:
  - url: http://localhost:8080

paths:
  /dispatch:
    post:
      summary: Dispatch erstellen
      operationId: createDispatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DispatchRequestDto'
      responses:
        '200':
          description: Dispatch erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DispatchCreatedResponseDto'

  /dispatch/{number}:
    get:
      summary: Status eines Dispatch abrufen
      operationId: getDispatchStatus
      parameters:
        - name: number
          in: path
          required: true
          schema:
            type: string
          description: Dispatch-Nummer
      responses:
        '200':
          description: Status erfolgreich abgerufen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DispatchStatusResponseDto'

    delete:
      summary: Dispatch stornieren
      operationId: cancelDispatch
      parameters:
        - name: number
          in: path
          required: true
          schema:
            type: string
          description: Dispatch-Nummer
      responses:
        '204':
          description: Erfolgreich gelöscht

components:
  schemas:

    DispatchRequestDto:
      type: object
      properties:
        customerNumber:
          type: integer
          example: 12345
        prescriptions:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionRequestDto'

    PrescriptionRequestDto:
      type: object
      properties:
        patient:
          $ref: '#/components/schemas/PatientRequestDto'
        positions:
          type: array
          items:
            $ref: '#/components/schemas/PositionRequestDto'

    PatientRequestDto:
      type: object
      properties:
        firstName:
          type: string
          example: Max
        lastName:
          type: string
          example: Mustermann

    PositionRequestDto:
      type: object
      properties:
        medication:
          type: string
          example: Ibuprofen
        quantity:
          type: integer
          example: 2

    DispatchCreatedResponseDto:
      type: object
      properties:
        dispatchId:
          type: string
          example: "DISP-123456"

    DispatchStatusResponseDto:
      type: object
      properties:
        dispatchId:
          type: string
        status:
          type: string
          example: "IN_PROGRESS"